# Generated by Django 5.2.1 on 2026-03-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_conent',
            new_name='comment_content',
        ),
    ]
