# Generated by Django 5.2.1 on 2026-03-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_comment_conent_comment_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
